name: Build Installer

on:
  push:
    branches: [ tea-shop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install pillow

      - name: Build EXE with PyInstaller
        run: |
          python -m eel main.py web --add-data "data:data" --onefile --noconsole --icon=bill.png

      - name: Install Inno Setup
        run: |
          choco install innosetup --yes

      - name: Run Inno Setup Compiler
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" Setup.iss

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: tea-shop-installer
          path: Output/*.exe


          # … your existing build and Inno Setup steps …

      - name: Create or update GitHub Release
        id: release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: "TeaShop v1.0"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload installer to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: installer/Output/TeaShopInstaller.exe
          asset_name: ChaiTime-BillingSoftware.exe
          asset_content_type: application/octet-stream

      - name: Upload portable EXE to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: dist/main.exe
          asset_name: Chai-time-BSPortable.exe
          asset_content_type: application/octet-stream

