name: Build Installer & Release

permissions:
  contents: write

on:
  push:
    branches: [ tea-shop ]
  workflow_dispatch:

env:
  RELEASE_VERSION: v1.0.${{ github.run_number }}

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller pillow

      - name: Build portable EXE with PyInstaller
        run: |
          python -m eel main.py web --add-data "data:data" --onefile --noconsole --icon=bill.png


      - name: Install Inno Setup
        run: |
          choco install innosetup --yes

      - name: Compile installer with Inno Setup
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' 'setup.iss'



      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body: |
            - Portable EXE built with PyInstaller  
            - Inno Setup installer  
          draft: false
          prerelease: false

      # ─── Upload the PyInstaller EXE ───────────────────────────────────────────
      - name: Upload Portable EXE
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist\main.exe
          asset_name: feedmd-portable.exe
          asset_content_type: application/octet-stream

      # ─── Upload the Inno Setup installer ─────────────────────────────────────
      - name: Upload Installer
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release\setup.exe
          asset_name: feedmd-installer.exe
          asset_content_type: application/octet-stream