# name: Build Installer & Release

# permissions:
#   contents: write

# on:
#   push:
#     branches: [ tea-shop ]
#   workflow_dispatch:

# env:
#   RELEASE_VERSION: v1.0.${{ github.run_number }}

# jobs:
#   build-and-release:
#     runs-on: windows-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.10'

#       - name: Install Python dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt pyinstaller pillow

#       - name: Build portable EXE with PyInstaller
#         run: |
#           python -m eel main.py web --add-data "data;data" --onefile --noconsole --icon=bill.png


#       - name: Install Inno Setup
#         run: |
#           choco install innosetup --yes

#       - name: Compile installer with Inno Setup
#         run: |
#           & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' 'setup.iss'



      - uses: actions/checkout@v3
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/main.exe
          asset_name: ChaiTime-BSPostable.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "Releasing portable exe"

      - uses: actions/checkout@v3
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: output/*.exe
          asset_name: ChaiTime-BSSetup.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "Releasing setup exe"