name: Build Installer & Release

permissions:
  contents: write

on:
  push:
    branches: [ tea-shop ]
  workflow_dispatch:

env:
  RELEASE_VERSION: v1.0.${{ github.run_number }}

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller pillow

      - name: Build portable EXE with PyInstaller
        run: |
          pyinstaller main.py --onefile --noconsole

      - name: Install Inno Setup
        run: |
          choco install innosetup --yes

      - name: Compile installer with Inno Setup
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' 'Setup.iss'

      - name: Create or update GitHub Release
        id: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: "TeaShop ${{ env.RELEASE_VERSION }}"

      - name: Upload portable EXE to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: dist/main.exe
          asset_name: TeaShopPortable-${{ env.RELEASE_VERSION }}.exe
          asset_content_type: application/octet-stream
          token: ${{ secrets.PAT_TOKEN }}

      - name: Upload installer to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: Output/*.exe
          asset_name: TeaShopInstaller-${{ env.RELEASE_VERSION }}.exe
          asset_content_type: application/octet-stream
          token: ${{ secrets.PAT_TOKEN }}

# --------------------------------------------
# IMPORTANT:
# Ensure you have a classic PAT in Secrets.PAT_TOKEN with full repo scope.
