name: Test Release

permissions:
  contents: write

on:
   push:
     branches: [ tea-shop ]

env:
  RELEASE_VERSION: v1.0.${{ github.run_number }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body: |
            Automated release of version ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload main.py to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.py
          asset_name: ChaiTime-BSPostable.exe
          tag: ${{ env.RELEASE_VERSION }}
          overwrite: true
          body: "Releasing portable exe"

      - name: Upload setup.iss to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: setup.iss
          asset_name: ChaiTime-BSSetup.exe
          tag: ${{ env.RELEASE_VERSION }}
          overwrite: true
          body: "Releasing setup exe"
